version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - nest-mysql
    env_file:
      - .env
    networks:
      - bill  

  nest-mysql:
    image: mysql
    container_name: nest-mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - bill    

volumes:
  nest-mysql:
    name: nest-mysql-db

networks:
  bill:
    name: bill